# Generated by Django 3.2.19 on 2023-07-07 22:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('meal_type', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner')], default=0)),
                ('preptime_in_minutes', models.DecimalField(decimal_places=1, max_digits=3)),
                ('calories_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('protein_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fat_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('carbs_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('day_type', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (7, 'Sunday')], default=0)),
                ('mealplans', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealplanner.mealplan')),
            ],
        ),
    ]
