# Generated by Django 3.2.19 on 2023-07-13 00:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('meal_type', models.IntegerField(choices=[(0, 'Breakfast'), (1, 'Lunch'), (2, 'Dinner')], default=0)),
                ('preptime_in_minutes', models.DecimalField(decimal_places=1, max_digits=3)),
                ('calories_in_grams', models.DecimalField(decimal_places=1, max_digits=5)),
                ('protein_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('fat_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
                ('carbs_in_grams', models.DecimalField(decimal_places=1, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='MealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meals', models.ManyToManyField(to='mealplanner.Meal')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='meal_plan', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
