# Generated by Django 3.2.19 on 2023-06-09 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='calories_g',
            new_name='calories_in_grams',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='carbs',
            new_name='carbs_in_grams',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='fat_g',
            new_name='fat_in_grams',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='mealtype',
            new_name='meal_type',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='preptime_mins',
            new_name='preptime_in_minutes',
        ),
        migrations.RenameField(
            model_name='meal',
            old_name='protein_g',
            new_name='protein_in_grams',
        ),
    ]
