# Generated by Django 3.2.19 on 2023-07-12 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='day_type',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='mealplans',
        ),
    ]
