# Generated by Django 3.2.19 on 2023-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0002_auto_20230712_1430'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='calories_in_grams',
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
