# Generated by Django 3.2.19 on 2023-07-12 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mealplanner', '0003_alter_meal_calories_in_grams'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='mealplans',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='meals', to='mealplanner.mealplan'),
        ),
    ]
